# Generated by Django 5.1.7 on 2025-06-16 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_advertisement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisement',
        ),
    ]
