# Generated by Django 5.1.7 on 2025-04-28 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='contry',
            new_name='country',
        ),
    ]
