# Generated by Django 5.1.7 on 2025-04-29 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_contry_userprofile_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_pciture',
            new_name='profile_picture',
        ),
    ]
