# Generated by Django 3.1 on 2025-03-04 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20250215_2051'),
        ('category', '0002_auto_20250212_2058'),
    ]

    operations = [
    ]
