# Generated by Django 5.1.7 on 2025-05-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_merge_20250304_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
